[package]
name = "copycat_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10"
log = "0.4"
clap = { version = "4.4.2", features = ["derive"] }
mailbox_client = { git="ssh://git@github.com/qusuyan/mailbox.git" }
copycat_utils = { path="../copycat_utils" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full"] }
